### ISSUE TITLE
Document the Onboarding Process 🔥

### ISSUE THREAD

**Issue by tgraham-ucsc** [cdp-ucsc/doc#19]
- Local Development set-up
  - VSCode, Pyenv, Venv
- Access
  - github, Fivetran, dbt Cloud, Snowflake

**Comment by insuhpak** [comment]
@jtomkins is going to contribute to GitHub instructions!

**Comment by jtomkins** [comment]
@tgraham-ucsc contributed to  GitHub instructions and is tracked in this [PR](https://github.com/cdp-ucsc/doc/pull/29) 

[content](http://localhost:3000/doc/docs/program_overview/practitioner/onboarding/github_setup_instructions)

![image](https://github.com/cdp-ucsc/doc/assets/8420258/e88977e2-50cd-4673-9a4f-0f82881a3b8b)
