### ISSUE TITLE
Doc - dbt core upgrade guide

### ISSUE THREAD

**Issue by insuhpak** [cdp-ucsc/doc#35]
***
Related items: 
- Discussion [v1.5 announcement](https://github.com/orgs/cdp-ucsc/discussions/111)
- Discussion ['Establish dbt core version updgrade process'](https://github.com/orgs/cdp-ucsc/discussions/112)

- Issue branch [35-dbt-core-upgrade-guide](https://github.com/cdp-ucsc/doc/tree/35-dbt-core-upgrade-guide)
***

Wait until the move from single to multi tenant is complete before actually upgrading versions.
Edit: Single to multi tenant move is complete ✅

***

Work in progress guide can be found here [doc/cdp-docs/docs/program_overview/practitioner/guides/upgrading_dbt_core_version_guide.md](https://github.com/cdp-ucsc/doc/blob/35-dbt-core-upgrade-guide/cdp-docs/docs/program_overview/practitioner/guides/upgrading_dbt_core_version_guide.md)

The guide is based on our previous upgrade experience ([PR 65 dbt core v132 to v144](https://github.com/cdp-ucsc/dbt-pilot/pull/65)).

The guide provides instructions on how to upgrade core versions. A main feature of the guide is the provided issue and PR templates that the user should use to guide them through the upgrade.

Currently, the guide is stored under Practitioner Resources/Guides. I personally think this may not be the best place for this type of guide and that we may want to discuss a different location/organization for this guide and similar guides to come. 

Local Build of the guide:
![Image](https://github.com/cdp-ucsc/doc/assets/83252857/884c28d3-bf7c-40c6-83ae-365315622330)

Example of the PR if you copy and paste the template included in the guide:
- [link](https://github.com/cdp-ucsc/doc/pull/38)
- screenshot:
![Image](https://github.com/cdp-ucsc/doc/assets/83252857/e04a422c-5fb5-4738-a16d-1696394c58b7)

Please review and comments/suggestions 😁. Once everyone has had a chance to contribute we will create a PR to add this document.

**Comment by tgraham-ucsc** [comment]
@insuhpak  - thanks for writing this up looks good!! I'd like to widen the scope a bit to include the overall process for planning, testing and ultimately implementing a dbt upgrade.  I'm interested in the table audit code, perhaps this is something we can automate with dbt-cloud 🤔.    Do you think this doc is part of a larger group that would include the overall process of upgrading dbt?  Thanks!

**Comment by insuhpak** [comment]
@tgraham-ucsc I don't think I have a thorough understanding of the fffuull scope, but in general, I think we can continue to add to this document. We will probably need to reorganize it as new information comes in. But I think of it as a pro if all upgrade-related information is one document. Of course, as we add we can decide to split it up. I know the "back end" stuff with dbt cloud can be elaborated on. And I think that information is appropriate to add to this document. 

I think some of the high-level tests can definitely be automated with a job in dbt-cloud! I can work on that when we begin to upgrade.

**Comment by insuhpak** [comment]
Hi @tgraham-ucsc I took another pass at the dbt version upgrade doc you can find [here](https://github.com/cdp-ucsc/doc/blob/35-dbt-core-upgrade-guide/cdp-docs/docs/program_overview/practitioner/guides/upgrading_dbt_version_guide.md).

My hope is that the documentation now reads with more emphasis on upgrading dbt Cloud as the main objective. Essentially, everything besides step 7 is upgrading in dbt cloud. Step 7 is the one thing that needs to be updated so that when the upgrade is pushed to main local developers can upgrade their workstations right after.

I would also say the documentation is pretty specific with some of the instructions. I am not sure whether being that level of specificity is going to be a pro or con in the long run but my reasoning was:
- If we have multiple projects being upgraded by different individuals, then a detailed guide will keep the process uniform.
- The naming conventions and instructions on how to track related issues will help organize the information so looking back at previous upgrades is easier.
- Hopefully, any core team member can follow these instructions to upgrade.

Let me know what you think.

**Comment by insuhpak** [comment]
Closing this issue due to the sunsetting of the pilot project.
