### ISSUE TITLE
Update SQL style guide to include code examples that illustrate both good and bad

### ISSUE THREAD

**Issue by magants** [cdp-ucsc/doc#4]
A few style guides include sections that illustrate both good and bad code.

Update the [UCSC style guide](https://github.com/cdp-ucsc/dbt-pilot/wiki/Style-Guide-Draft#sql-style-guide) to include this. 

style guides:
https://github.com/brooklyn-data/co/blob/main/sql_style_guide.md#credits
https://github.com/mattm/sql-style-guide#mazurs-sql-style-guide
https://github.com/dbt-labs/corp/blob/b5c6f55b9e7594e1a1e562edf2378b6dd78a1119/dbt_coding_conventions.md

**Comment by insuhpak** [comment]
Closing this issue since [Ucsc sql style guide #5 PR](https://github.com/cdp-ucsc/doc/pull/5) has been merged and closed.
