### ISSUE TITLE
Doc - Onboarding documentation refresh

### ISSUE THREAD

**Issue by insuhpak** [cdp-ucsc/doc#48]
General refresh of the Onboarding section of the documentation.

- Add a "landing" page for the section ➡️ **Onboarding Introduction**
- Add new documentation for dbt Cloud ➡️ **dbt Cloud Setup**, Snowflake ➡️ **Snowflake Setup**, and Fivetran ➡️ **Fivetran Setup**
- Update dbt Core documentation
  - Issue #46 is included in this larger issue

**Comment by insuhpak** [comment]
@tgraham-ucsc 
Hi Todd, I have gotten some work done regarding this issue and want to get it in front of you before continuing on. 

The main changes have been the addition of the landing page [**Onboarding Introduction**](https://github.com/cdp-ucsc/doc/blob/46-doc-review-workstation-set-up-instructions-macos-specific/cdp-docs/docs/program_overview/practitioner/onboarding/onboarding_introduction.md).

Based on the flow of the Introduction page, the following have been added
- [dbt Cloud Setup](https://github.com/cdp-ucsc/doc/blob/46-doc-review-workstation-set-up-instructions-macos-specific/cdp-docs/docs/program_overview/practitioner/onboarding/dbt_cloud_setup.md)
  - Should get people up and running and be able to run SQL queries. 
  - Should get everyone up and running but aimed more towards Business/Data Analysts.
- [Snowflake Setup](https://github.com/cdp-ucsc/doc/blob/46-doc-review-workstation-set-up-instructions-macos-specific/cdp-docs/docs/program_overview/practitioner/onboarding/snowflake_setup.md)
  - Basic navigation of different roles, worksheets, and data.
  - Aimed towards AEs. 
- Fivetran Setup
  - Currently empty. 
  - We could make this documentation more involved and have it aimed at DEs. But someone from Ken's team would probably have to do the documentation. If you want it general, I can write something that is similar to what I currently have for Snowflake.

I still need to rework the dbt Core Setup documentation. But in general, that will be aimed for AE/DEs.

**Comment by tgraham-ucsc** [comment]
Fantastic, I'll take a look.  Great stuff!

**Comment by insuhpak** [comment]
Lapsed issue closing due to clean up.
