### ISSUE TITLE
Proposal > Git branching strategy

### ISSUE THREAD

**Issue by insuhpak** [cdp-ucsc/doc#60]
[You can find Andrew Taft's input here.](https://github.com/user-attachments/files/16461942/Andrew.s.Input.pdf)

This workflow/strategy is referred to as "Feat to UAT, Ready Feat to Main".

### Workflow:
1. Product Backlog Item becomes a Sprint Item.
2. Sprint Item requires code changes. For the sake of this example, we will call it a feature.
3. Developer creates a feature branch from main.
4. Developer develops in feature branch.
5. Feature branch is ready for user testing. Developer via a PR initiates the feature branch to be merged into UAT.
6. If there are merge conflicts, then go back to step 4. to resolve the conflicts. Else approve the PR to UAT.
7. Users test in UAT environment. If users have feedback that requires code changes, then document the feedback in the Sprint Item and go back to step 4.
8. Users accept the feature. The developer via a PR initiates the feature branch to be merged into main.
9. The PR to main is reviewed thoroughly. If there are issues then go back to step 4.
10. If the PR is approved, the feature branch is merged into main and then deleted. This closes the PR to main.
11. Update uat with main (i.e. merge main into uat).

### Git Diagram:
![Image](https://github.com/user-attachments/assets/f6897b9a-2630-4450-8c0d-f58f6d113545)
> [Lucidchart link.](https://lucid.app/lucidchart/5d4f3e21-7c29-4f46-b506-751568563ee2/edit?invitationId=inv_d2b50fcb-c1a5-49e6-b2ee-04edcccec42b&page=qnWU~.8Q7Ezn#)

### Request:
Per Andrew's input email, he stated that he would test this strategy in the student-analytics project. I am not sure if others contributing to the student-analytics project are also using this strategy. I am also not fully aware of the status and experience taking place in student-analytics.

In the financial-analytics, I have also decided to test this strategy out. There are not many active developers (just Jen Walker and I) so it is easy to control the workflow at this moment. But before I can test this strategy, the existing branches and features need to be sorted and cleaned (tracked by https://github.com/cdp-ucsc/financial-analytics/issues/85).

I want to confirm that the Program Managers agree with this effort in both the student-analytics and financial-analytics projects. Furthermore, inquire if the Program Managers see an area of improvement or communication that is needed with the developers' group. Or other actionable tasks that are needed related to this topic.

**Comment by insuhpak** [comment]
@jemduffy-ucsc Hi Jessica, here is the write-up on the git branching strategy as we discussed. Please let me know if you have questions.

**Comment by jemduffy-ucsc** [comment]
Per 8/6/2024 PM meeting with @jemduffy-ucsc , @tgraham-ucsc , and @psbauman-ucsc : The  proposed git strategy is confirmed for testing.

**Comment by JaNickel** [comment]
This is a clean logical way to handle writing/testing/merging of features.
I think it is an improvement on the previous strategy
